python run_export_gene_feature_matrix.py 20200303_hMTG_V11_4000gene_best_sample/data assignedBarcodes/barcodes_dendrite.h5 exportedFeatures/dendrite.shp exportedGeneFeatureMatrices/dendrite 10 
python run_export_gene_feature_matrix.py 20200430_hMTG_best_sample_V11_4000gene/data assignedBarcodes/barcodes_dendrite.h5 exportedFeatures/dendrite.shp exportedGeneFeatureMatrices/dendrite 10 
python run_export_gene_feature_matrix.py 20200615_hMTG_4000gene_best_sample/data assignedBarcodes/barcodes_dendrite.h5 exportedFeatures/dendrite.shp exportedGeneFeatureMatrices/dendrite 10 
python run_export_gene_feature_matrix.py 20200818_STG_H1/data assignedBarcodes/barcodes_dendrite.h5 exportedFeatures/dendrite.shp exportedGeneFeatureMatrices/dendrite 10 
python run_export_gene_feature_matrix.py 20201003_STG_4000gene_V11/data assignedBarcodes/barcodes_dendrite.h5 exportedFeatures/dendrite.shp exportedGeneFeatureMatrices/dendrite 10 
